project(assimp)

include(zlibstatic.cmake)
include(IrrXML.cmake)

set(ASSIMP_COMMON_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Assimp.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/BaseImporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/BaseProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/BaseProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Bitmap.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/CInterfaceIOWrapper.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/CInterfaceIOWrapper.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/CreateAnimMesh.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DefaultIOStream.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DefaultIOSystem.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DefaultProgressHandler.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/IFF.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ImporterRegistry.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/PostStepRegistry.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/RemoveComments.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SGSpatialSort.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SceneCombiner.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ScenePreprocessor.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ScenePreprocessor.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ScenePrivate.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SkeletonMeshBuilder.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SpatialSort.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SplitByBoneCountProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SplitByBoneCountProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/StandardShapes.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Subdivision.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/TargetAnimation.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/TargetAnimation.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Version.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/VertexTriangleAdjacency.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/VertexTriangleAdjacency.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/scene.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/simd.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/simd.h
)

set(ASSIMP_LOGGING_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DefaultLogger.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FileLogStream.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/StdOStreamLogStream.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Win32DebugLogStream.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/include/assimp/DefaultLogger.hpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/include/assimp/LogStream.hpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/include/assimp/Logger.hpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/include/assimp/NullLogger.hpp
)

set(ASSIMP_EXPORTER_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/AssimpCExport.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Exporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/include/assimp/BlobIOSystem.h
)

set(ASSIMP_POSTPROCESSING_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/CalcTangentsProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/CalcTangentsProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ComputeUVMappingProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ComputeUVMappingProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ConvertToLHProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ConvertToLHProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DeboneProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DeboneProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DropFaceNormalsProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/DropFaceNormalsProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/EmbedTexturesProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/EmbedTexturesProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FindDegenerates.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FindDegenerates.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FindInstancesProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FindInstancesProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FindInvalidDataProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FindInvalidDataProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FixNormalsStep.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FixNormalsStep.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/GenFaceNormalsProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/GenFaceNormalsProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/GenVertexNormalsProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/GenVertexNormalsProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ImproveCacheLocality.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ImproveCacheLocality.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/JoinVerticesProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/JoinVerticesProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/LimitBoneWeightsProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/LimitBoneWeightsProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/MakeVerboseFormat.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/MakeVerboseFormat.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OptimizeGraph.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OptimizeGraph.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OptimizeMeshes.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OptimizeMeshes.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/PolyTools.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/PretransformVertices.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/PretransformVertices.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ProcessHelper.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ProcessHelper.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/RemoveRedundantMaterials.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/RemoveRedundantMaterials.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/RemoveVCProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/RemoveVCProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ScaleProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ScaleProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SortByPTypeProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SortByPTypeProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SplitLargeMeshes.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/SplitLargeMeshes.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/TextureTransform.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/TextureTransform.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/TriangulateProcess.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/TriangulateProcess.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ValidateDataStructure.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ValidateDataStructure.h
)

set(ASSIMP_MATERIALSYSTEM_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/MaterialSystem.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/MaterialSystem.h
)

set(ASSIMP_STEP_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer/StepFile/StepFileGen1.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer/StepFile/StepFileGen2.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer/StepFile/StepFileGen3.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer/StepFile/StepFileImporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer/StepFile/StepFileImporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/Importer/StepFile/StepReaderGen.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/STEPFile.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/StepExporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/StepExporter.h
)

set(ASSIMP_COLLADA_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ColladaExporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ColladaExporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ColladaHelper.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ColladaLoader.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ColladaLoader.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ColladaParser.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ColladaParser.h
)

set(ASSIMP_IRRMESH_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/IRRMeshLoader.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/IRRMeshLoader.h
)

set(ASSIMP_IRR_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/IRRLoader.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/IRRLoader.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/IRRShared.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/IRRShared.h
)

set(ASSIMP_OBJ_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjExporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjExporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjFileData.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjFileImporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjFileImporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjFileMtlImporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjFileMtlImporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjFileParser.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjFileParser.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/ObjTools.h
)

set(ASSIMP_OGRE_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreBinarySerializer.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreBinarySerializer.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreImporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreImporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreMaterial.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreParsingUtils.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreStructs.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreStructs.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreXmlSerializer.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/OgreXmlSerializer.h
)

set(ASSIMP_FBX_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXAnimation.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXBinaryTokenizer.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXCommon.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXCompileConfig.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXConverter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXConverter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXDeformer.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXDocument.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXDocument.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXDocumentUtil.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXExportNode.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXExportNode.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXExportProperty.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXExportProperty.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXExporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXExporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXImportSettings.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXImporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXImporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXMaterial.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXMeshGeometry.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXMeshGeometry.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXModel.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXNodeAttribute.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXParser.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXParser.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXProperties.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXProperties.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXTokenizer.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXTokenizer.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXUtil.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/FBXUtil.h
)

set(ASSIMP_RAW_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/RawLoader.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/RawLoader.h
)

set(ASSIMP_STL_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/STLExporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/STLExporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/STLLoader.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/STLLoader.h
)

set(ASSIMP_3D_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/UnrealLoader.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/UnrealLoader.h
)

set(ASSIMP_GLTF_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2Asset.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2Asset.inl
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2AssetWriter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2AssetWriter.inl
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2Exporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2Exporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2Importer.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTF2Importer.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFAsset.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFAsset.inl
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFAssetWriter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFAssetWriter.inl
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFExporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFExporter.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFImporter.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/code/glTFImporter.h
)

set(ASSIMP_IRRXML_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/include/assimp/irrXMLWrapper.h
)

set(ASSIMP_UNZIP_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/unzip/crypt.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/unzip/ioapi.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/unzip/ioapi.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/unzip/unzip.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/unzip/unzip.h
)

set(ASSIMP_POLY2TRI_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/common/shapes.cc
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/common/shapes.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/common/utils.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/advancing_front.cc
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/advancing_front.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/cdt.cc
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/cdt.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/sweep.cc
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/sweep.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/sweep_context.cc
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/poly2tri/poly2tri/sweep/sweep_context.h
)

set(ASSIMP_CLIPPER_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/clipper/clipper.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/clipper/clipper.hpp
)

set(ASSIMP_OPENDDL_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/code/DDLNode.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/code/OpenDDLCommon.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/code/OpenDDLExport.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/code/OpenDDLParser.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/code/OpenDDLStream.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/code/Value.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/include/openddlparser/DDLNode.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/include/openddlparser/OpenDDLCommon.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/include/openddlparser/OpenDDLExport.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/include/openddlparser/OpenDDLParser.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/include/openddlparser/OpenDDLParserUtils.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/include/openddlparser/OpenDDLStream.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/assimp/4.1.0/contrib/openddlparser/include/openddlparser/Value.h
)

set()
