set(MINIZIP_FILES
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_crypt_brg.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_crypt.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_crypt.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_os.cpp
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_os.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_strm_raw.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_strm_wzaes.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_strm_wzaes.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_strm_zlib.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_strm_zlib.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_strm.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_zip.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz_zip.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/mz.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/zip.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/zip/miniz.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/aeskey.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/hmac.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/sha2.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/aestab.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/aescrypt.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/aesopt.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/sha1.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/brg_types.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/sha2.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/hmac.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/brg_endian.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/aes.h
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/aestab.c
    ../../The-Forge/Common_3/ThirdParty/OpenSource/minizip/lib/brg/sha1.h
)
