
set(RENDER_LINK_LIBS "")

if(${METAL} MATCHES ON)
    set(RENDERER_FILES ${RENDERER_FILES} ${METAL_FILES})
endif()

if(${VULKAN} MATCHES ON)
    set(RENDERER_FILES ${RENDERER_FILES} ${VULKAN_FILES})
endif()

if(${DX11} MATCHES ON)
    set(RENDERER_FILES ${RENDERER_FILES} ${DX11_FILES} ${AGS_INCLUDE_FILES})
endif()

if(${DX12} MATCHES ON)
    set(RENDERER_FILES ${RENDERER_FILES} ${DX12_FILES} ${AGS_INCLUDE_FILES})
endif()

if(${WINDOWS} MATCHES ON)
    set(RENDERER_FILES ${RENDERER_FILES} ${NVAPI_INCLUDE_FILES})
endif()

add_library(Renderer STATIC
    ${RENDERER_SOURCE_FILES}
    ${RENDERER_INCLUDE_FILES}
    ${RENDERER_FILES}
)

target_link_libraries(Renderer PUBLIC ${RENDER_LIBRARIES})
